[package]
name = "block-client-rs"
authors = ["Aurora Labs <hello@aurora.dev>"]
version = "0.1.4"
edition = "2024"
readme = "README.md"
repository = "https://github.com/aurora-is-near/block-client-rs.git"
description = "Client for the block API service"
keywords = ["block", "client", "api", "service", "grpc"]
publish = false
license = "CC0-1"

[dependencies]
anyhow = "1"
aurora-refiner-types = { git = "https://github.com/aurora-is-near/borealis-engine-lib.git", tag = "0.31.2-2.13.2" }
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
hex = "0.4"
lz4 = "1"
num-derive = "0.5"
num-traits = "0.2"
prost = "0.14"
rand = "0.10"
serde = { version = "1", features = ["derive"] }
serde_cbor = "0.11"
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tonic = { version = "0.14", features = ["channel"] }
tonic-prost = "0.14"

[build-dependencies]
tonic-prost-build = "0.14"
walkdir = "2"

[features]

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }

missing_errors_doc = "allow"
