[package]
name = "block-client-rs"
authors = ["Aurora Labs <hello@aurora.dev>"]
version = "0.1.3"
edition = "2024"
readme = "README.md"
repository = "https://github.com/aurora-is-near/block-client-rs.git"
description = "Client for blocks API service"
keywords = ["block", "client", "api", "service", "grpc"]
publish = false
license = "CC0-1"

[dependencies]
anyhow = "1"
borealis-nats-client = { git = "ssh://git@github.com/aurora-is-near/borealis-rs", tag = "1.4.21-2.7.1-rc.1" }
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
prost = "0.14"
tonic = { version = "0.14", features = ["channel"] }
tonic-prost = "0.14"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }

[build-dependencies]
tonic-prost-build = "0.14"
walkdir = "2"

[features]

[lints.clippy]
all = "deny"
pedantic = "deny"
nursery = "deny"
